Algoritmo "manzano"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/11/2022
Var
// Seção de Declarações das variáveis 
num1,num2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
num1 <- 14
repita
  num1 <- num1+1
  num2 <- num1*num1
  escreval (num1," ao quadrado =",num2)
ate (num1 = 200)

Fimalgoritmo