Algoritmo "resultado do quadrado"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler dois inteiros (variáveis A e B) e imprimir o resultado
               // do quadrado da diferença do primeiro valor pelo segundo.
// Autor(a)    : Paloma Gomes Lira
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis 
varA:real
varB:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo